# Generated by Django 4.2.20 on 2026-03-14 01:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0003_drop_legacy_supplier_column'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='supplier_name',
            field=models.CharField(blank=True, max_length=160),
        ),
    ]
